/* Demo data used when Supabase is not configured */

export const DEMO_RECIPES = [
  {
    id: '1',
    name: 'Shakshuka with Feta',
    categories: ['Breakfast', 'Dinner'],
    photo_url: null,
    prep_time: '10 min',
    cook_time: '20 min',
    servings_base: 2,
    yield: '2 servings',
    ingredients: [
      { quantity: '2', unit: 'tbsp', item: 'olive oil', notes: '' },
      { quantity: '1', unit: '', item: 'onion, diced', notes: '' },
      { quantity: '1', unit: '', item: 'red bell pepper, diced', notes: '' },
      { quantity: '3', unit: 'cloves', item: 'garlic, minced', notes: '' },
      { quantity: '1', unit: 'tsp', item: 'cumin', notes: '' },
      { quantity: '1', unit: 'tsp', item: 'smoked paprika', notes: '' },
      { quantity: '1', unit: 'can', item: 'crushed tomatoes', notes: '400g' },
      { quantity: '4', unit: '', item: 'eggs', notes: '' },
      { quantity: '75', unit: 'g', item: 'feta cheese', notes: 'crumbled' },
      { quantity: '2', unit: 'tbsp', item: 'fresh parsley', notes: 'chopped' },
    ],
    directions: [
      { step: 1, text: 'Heat oil in a large skillet over medium heat. Add onion and pepper, cook until softened, about 8 minutes.' },
      { step: 2, text: 'Add garlic, cumin, and paprika. Cook 1 minute until fragrant.' },
      { step: 3, text: 'Add crushed tomatoes and season with salt and pepper. Simmer 10 minutes.' },
      { step: 4, text: 'Make wells in the sauce and crack in the eggs. Cover and cook until whites are set, 5–7 minutes.' },
      { step: 5, text: 'Top with feta and parsley. Serve immediately with crusty bread.' },
    ],
    source_label: 'NYT Cooking',
    source_url: null,
    author_notes: 'Great for brunch. The sauce can be made ahead and refrigerated up to 3 days.',
    serving_suggestions: 'Serve with warm pita or crusty sourdough.',
    nutrition: { calories: 380, protein: 22, fat: 24, carbs: 18, is_estimated: true },
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Lemon Pasta with Ricotta',
    categories: ['Lunch', 'Dinner'],
    photo_url: null,
    prep_time: '5 min',
    cook_time: '15 min',
    servings_base: 2,
    yield: '2 servings',
    ingredients: [
      { quantity: '200', unit: 'g', item: 'spaghetti', notes: '' },
      { quantity: '120', unit: 'g', item: 'ricotta', notes: 'full-fat' },
      { quantity: '1', unit: '', item: 'lemon, zested and juiced', notes: '' },
      { quantity: '30', unit: 'g', item: 'parmesan, grated', notes: '' },
      { quantity: '2', unit: 'tbsp', item: 'olive oil', notes: 'extra virgin' },
      { quantity: '2', unit: 'cloves', item: 'garlic', notes: '' },
      { quantity: '¼', unit: 'tsp', item: 'chilli flakes', notes: 'optional' },
    ],
    directions: [
      { step: 1, text: 'Cook pasta in well-salted boiling water until al dente. Reserve 1 cup pasta water before draining.' },
      { step: 2, text: 'In a large bowl, mix ricotta, lemon zest, half the juice, parmesan, and 1 tbsp olive oil. Season.' },
      { step: 3, text: 'Gently warm garlic in remaining oil for 1 minute. Add chilli flakes.' },
      { step: 4, text: 'Add hot pasta to ricotta bowl and toss, adding pasta water to loosen to a creamy sauce.' },
      { step: 5, text: 'Finish with lemon juice to taste and black pepper.' },
    ],
    source_label: null,
    source_url: null,
    author_notes: null,
    serving_suggestions: null,
    nutrition: { calories: 520, protein: 20, fat: 18, carbs: 68, is_estimated: true },
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Thai Basil Chicken',
    categories: ['Dinner'],
    photo_url: null,
    prep_time: '10 min',
    cook_time: '15 min',
    servings_base: 2,
    yield: '2 servings',
    ingredients: [
      { quantity: '400', unit: 'g', item: 'ground chicken', notes: '' },
      { quantity: '3', unit: 'cloves', item: 'garlic, minced', notes: '' },
      { quantity: '2', unit: '', item: 'Thai chillies, sliced', notes: 'or 1 jalapeño' },
      { quantity: '1', unit: 'cup', item: 'Thai basil leaves', notes: 'packed' },
      { quantity: '2', unit: 'tbsp', item: 'oyster sauce', notes: '' },
      { quantity: '1', unit: 'tbsp', item: 'fish sauce', notes: '' },
      { quantity: '1', unit: 'tsp', item: 'dark soy sauce', notes: '' },
      { quantity: '1', unit: 'tsp', item: 'sugar', notes: '' },
      { quantity: '2', unit: 'tbsp', item: 'vegetable oil', notes: '' },
      { quantity: '2', unit: '', item: 'fried eggs', notes: 'to serve' },
      { quantity: '2', unit: 'cups', item: 'jasmine rice', notes: 'cooked, to serve' },
    ],
    directions: [
      { step: 1, text: 'Combine oyster sauce, fish sauce, soy sauce, and sugar in a small bowl. Set aside.' },
      { step: 2, text: 'Heat oil in a wok or large skillet over high heat until smoking.' },
      { step: 3, text: 'Add garlic and chillies, stir-fry 30 seconds.' },
      { step: 4, text: 'Add chicken and stir-fry, breaking up clumps, until cooked through, 3–4 minutes.' },
      { step: 5, text: 'Add sauce and toss to coat. Remove from heat and stir in basil.' },
      { step: 6, text: 'Serve over rice, topped with a fried egg.' },
    ],
    source_label: 'Serious Eats',
    source_url: null,
    author_notes: 'Must use a very hot wok for the wok hei. Regular basil works but loses the authentic flavour.',
    serving_suggestions: null,
    nutrition: { calories: 480, protein: 38, fat: 22, carbs: 32, is_estimated: false },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Overnight Oats with Berries',
    categories: ['Breakfast'],
    photo_url: null,
    prep_time: '5 min',
    cook_time: '0 min',
    servings_base: 1,
    yield: '1 serving',
    ingredients: [
      { quantity: '½', unit: 'cup', item: 'rolled oats', notes: '' },
      { quantity: '½', unit: 'cup', item: 'milk', notes: 'or oat milk' },
      { quantity: '¼', unit: 'cup', item: 'Greek yoghurt', notes: '' },
      { quantity: '1', unit: 'tbsp', item: 'chia seeds', notes: '' },
      { quantity: '1', unit: 'tbsp', item: 'maple syrup', notes: '' },
      { quantity: '½', unit: 'tsp', item: 'vanilla extract', notes: '' },
      { quantity: '½', unit: 'cup', item: 'mixed berries', notes: 'fresh or frozen' },
    ],
    directions: [
      { step: 1, text: 'Combine oats, milk, yoghurt, chia seeds, maple syrup, and vanilla in a jar or container.' },
      { step: 2, text: 'Stir well, seal, and refrigerate overnight (at least 6 hours).' },
      { step: 3, text: 'Top with berries before serving. Add more milk if too thick.' },
    ],
    source_label: null,
    source_url: null,
    author_notes: null,
    serving_suggestions: 'Add granola for crunch.',
    nutrition: { calories: 320, protein: 14, fat: 8, carbs: 48, is_estimated: false },
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Roasted Cauliflower Soup',
    categories: ['Lunch', 'Dinner'],
    photo_url: null,
    prep_time: '15 min',
    cook_time: '45 min',
    servings_base: 4,
    yield: '4 servings',
    ingredients: [
      { quantity: '1', unit: '', item: 'large cauliflower, cut into florets', notes: '' },
      { quantity: '1', unit: '', item: 'onion, quartered', notes: '' },
      { quantity: '4', unit: 'cloves', item: 'garlic', notes: 'unpeeled' },
      { quantity: '3', unit: 'tbsp', item: 'olive oil', notes: '' },
      { quantity: '1', unit: 'L', item: 'vegetable stock', notes: '' },
      { quantity: '200', unit: 'ml', item: 'double cream', notes: '' },
      { quantity: '1', unit: 'tsp', item: 'nutmeg', notes: 'freshly grated' },
    ],
    directions: [
      { step: 1, text: 'Preheat oven to 200°C. Toss cauliflower, onion, and garlic with oil and season.' },
      { step: 2, text: 'Roast 30–35 minutes until golden at edges. Squeeze garlic from skins.' },
      { step: 3, text: 'Transfer to a pot, add stock, and bring to a simmer for 10 minutes.' },
      { step: 4, text: 'Blend until smooth. Stir in cream and nutmeg. Adjust seasoning.' },
    ],
    source_label: null,
    source_url: null,
    author_notes: null,
    serving_suggestions: 'Serve with a drizzle of truffle oil and crusty bread.',
    nutrition: null,
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Chocolate Lava Cake',
    categories: ['Desserts'],
    photo_url: null,
    prep_time: '15 min',
    cook_time: '12 min',
    servings_base: 2,
    yield: '2 cakes',
    ingredients: [
      { quantity: '100', unit: 'g', item: 'dark chocolate 70%', notes: 'chopped' },
      { quantity: '100', unit: 'g', item: 'unsalted butter', notes: 'plus extra for ramekins' },
      { quantity: '2', unit: '', item: 'eggs', notes: '' },
      { quantity: '2', unit: '', item: 'egg yolks', notes: '' },
      { quantity: '100', unit: 'g', item: 'caster sugar', notes: '' },
      { quantity: '2', unit: 'tbsp', item: 'plain flour', notes: '' },
      { quantity: '1', unit: 'pinch', item: 'sea salt', notes: '' },
    ],
    directions: [
      { step: 1, text: 'Preheat oven to 200°C. Butter and dust two ramekins with cocoa powder.' },
      { step: 2, text: 'Melt chocolate and butter together in a bowl over simmering water. Cool slightly.' },
      { step: 3, text: 'Whisk eggs, yolks, and sugar until pale and thick, about 3 minutes.' },
      { step: 4, text: 'Fold chocolate into egg mixture, then fold in flour and salt.' },
      { step: 5, text: 'Divide between ramekins. Bake 10–12 minutes until edges are set but centre jiggles.' },
      { step: 6, text: 'Rest 1 minute, then invert onto plates. Serve immediately.' },
    ],
    source_label: null,
    source_url: null,
    author_notes: 'Can be prepared up to stage 4 and refrigerated for up to 24 hours. Add 2 minutes to bake time from cold.',
    serving_suggestions: 'Serve with vanilla ice cream.',
    nutrition: { calories: 680, protein: 12, fat: 42, carbs: 62, is_estimated: false },
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const COOKBOOK_CATEGORIES = [
  { id: 'Breakfast',  icon: '🌅', label: 'Breakfast' },
  { id: 'Lunch',      icon: '☀️', label: 'Lunch' },
  { id: 'Dinner',     icon: '🌙', label: 'Dinner' },
  { id: 'Desserts',   icon: '🍰', label: 'Desserts' },
  { id: 'Appetizers', icon: '🥗', label: 'Appetizers' },
  { id: 'Snacks',     icon: '🍎', label: 'Snacks' },
  { id: 'Parties',    icon: '🎉', label: 'Parties' },
]

export const SHOPPING_CATEGORIES_ORDER = [
  'Bakery', 'Deli', 'Frozen', 'Beverages', 'Meat', 'Pantry', 'Dairy', 'Produce', 'Other'
]
